# Generated by Django 5.0.2 on 2024-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
